/**
 * Autogenerated by Thrift Compiler (0.14.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef judgement_CONSTANTS_H
#define judgement_CONSTANTS_H

#include "judgement_types.h"

namespace astraea { namespace thrift { namespace mq {

class judgementConstants {
 public:
  judgementConstants();

  std::map<JudgementType::type, std::string>  JudgementName;
};

extern const judgementConstants g_judgement_constants;

}}} // namespace

#endif
